########################
#  pda                 # 
########################
# # service
---
apiVersion: v1
kind: Service
metadata:
  name: alameter
  namespace: alameter
  labels:
    app: alameter
spec:
  ports:
  - port: 8999
    targetPort: 8999
    name: alameter
  selector:
    app: alameter

## deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alameter
  namespace: alameter
spec:
  selector:
    matchLabels:
      app : alameter
  template:
      metadata:
        labels:
          app: alameter
      spec:
        containers:
        - name: alameter
          image: prophetservice/alameter:latest
          imagePullPolicy: Never
          ports:
          - name: gui-alameter
            containerPort: 8999
          tty:  true
          # checking
          #livenessProbe:
          #  httpGet:
          #     path: /pda/
          #     port: 8999
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  timeoutSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          #readinessProbe:
          #  httpGet:
          #    path: /pda/api/
          #    port: 8999
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  timeoutSeconds: 10
          #  successThreshold: 1
          #  failureThreshold: 3
          volumeMounts:
          - mountPath: /opt/prophetstor/alameter/var
            name: depot
            subPath: alameter/alameter/alameter/var
          - name: localtime
            mountPath: "/etc/localtime"
            readOnly: true
          - mountPath: /var/log
            subPath: alameter/alameter/alameter/varlog
            name: depot   
          # mounted shared directory: /depot
          - mountPath: /depot
            name: depot
        #initContainers:
        #- name: init-mgmt
        #  image: prophetservice/mgmt:running
        #  imagePullPolicy: Never
        #  command: ["sh", "-c", "/opt/prophetstor/federatorai/bin/init-pda.sh"]
        #  volumeMounts:
        #  - name: federatorai
        #    mountPath: /opt/prophetstor/federatorai
        #restartPolicy: Always
        # mount rook shared file system
        volumes:
        - name: depot
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: rook-filesystem
              clusterName: rook-ceph
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: federatorai
          hostPath:
            path: /opt/prophetstor/federatorai
